-- Regional and Payment Analysis
-- Compare sales activity across regions and payment methods.


-- Question 20:
-- How many orders came from each region?

SELECT region,
       COUNT(*) AS total_orders
FROM retail_sales
GROUP BY region
ORDER BY total_orders DESC;


-- Question 21:
-- How much revenue did each region generate?

SELECT region,
       SUM(price * quantity) AS total_revenue
FROM retail_sales
GROUP BY region
ORDER BY total_revenue DESC;


-- Question 22:
-- How many units were sold in each region?

SELECT region,
       SUM(quantity) AS units_sold
FROM retail_sales
GROUP BY region
ORDER BY units_sold DESC;


-- Question 23:
-- Which regions generated more than $5,000 in revenue?

SELECT region,
       SUM(price * quantity) AS total_revenue
FROM retail_sales
GROUP BY region
HAVING SUM(price * quantity) > 5000
ORDER BY total_revenue DESC;


-- Question 24:
-- How many orders were paid for using each payment method?

SELECT payment_method,
       COUNT(*) AS total_orders
FROM retail_sales
GROUP BY payment_method
ORDER BY total_orders DESC;


-- Question 25:
-- How much revenue was generated by each payment method?

SELECT payment_method,
       SUM(price * quantity) AS total_revenue
FROM retail_sales
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- Question 26:
-- What is the average order revenue for each payment method?

SELECT payment_method,
       AVG(price * quantity) AS average_order_revenue
FROM retail_sales
GROUP BY payment_method
ORDER BY average_order_revenue DESC;
